### ISSUE TITLE
Better ending storyboards

### ISSUE THREAD

**Issue by Alexejhero** [Alexejhero/TutelQuest#4]
If camila makes them

- [x] improve regular ending storyboard
- [x] add new storyboard for rum ending

**Comment by budwheizzah** [comment]
In a nutshell, we originally wanted the end to reveal that Vedal was having an alcohol fueled fever dream:
-Wakes up, realizes he's probably been dreaming
-Neuro says hi and Vedal gives her a hug, getting over the stress of having lost her (our current end)
-Asks Neuro if she happens to know where his rum is... Neuro shrugs. The end.

With the rum, same thing but after Vedal hugs Neuro:
-As Neuro hands Vedal a rum bottle, "Wait, Neuro, where did you find this"?
-"I found it while you were passed out"
(leaves us wondering if this was actually a dream or not)

**Comment by Alexejhero** [comment]
idk this seems a bit too complicated to understand and a bit too meta

what i originally suggested was keeping the same ending storyboard and just improving it a bit, and for the rum ending drawing a separate scene where vedal is drinking the rum and ignoring neuro or smth

i want to let camila take the lead here and do whatever she wants

**Comment by budwheizzah** [comment]
Actually I love the drinking the rum and ignoring neuro LOL

Let's let camila cook, I just wanted to write my idea here she doesn't have to use any of it. o7
